# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys a Pipeline Factory Role into each account to execute actions in that account.

Parameters:
  pScanCodePipelineAccount:
    Type: String
  pOrganizationalUnitIds:
    Type: 'CommaDelimitedList'
    Default: "ou-1234-56789012,ou-0987-65432109"

Resources:
  rStackSetPipelineFactoryAssumedAccessRole:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: true
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: "IAM Role Deployment for PipelineFactory to assume into other accounts"
      OperationPreferences:
        MaxConcurrentCount: 10
      Parameters:
        - ParameterKey: pScanCodePipelineAccount
          ParameterValue: !Ref pScanCodePipelineAccount
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        - Regions:
            - !Ref AWS::Region
          DeploymentTargets:
            OrganizationalUnitIds: !Ref pOrganizationalUnitIds
      StackSetName: ScanCodePipeline-AssumedAccess-Role
      TemplateBody: |
        AWSTemplateFormatVersion: '2010-09-09'
        Description: Deploys a role into the account to execute actions in that account

        Parameters:
          pScanCodePipelineAccount:
            Type: 'String'

        Resources:
          rScanUpdateCodePipelineAssumedRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: ScanCodePipelineAssumedAccessRole
              Path: "/"
              AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Effect: Allow
                    Principal:
                      AWS:
                        - !Sub arn:aws:iam::${pScanCodePipelineAccount}:role/ScanUpdateCodePipeline
                    Action:
                      - sts:AssumeRole
              Policies:
                - PolicyName: ScanCodePipelineAssumedRole-CodePipelineStatus
                  PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                      - Sid: InvokeLambda
                        Effect: Allow
                        Action:
                          - codepipeline:PutJobFailureResult
                          - codepipeline:PutJobSuccessResult
                          - codepipeline:GetPipeline
                        Resource: "*"
